import { UIStringsDictionary, StringTemplateValues } from '@/types';

/**
 * Formats a template string containing `{key}` tokens with provided runtime values.
 *
 * @example
 * formatString('Negotiation Round {round}', { round: 2 }) // => 'Negotiation Round 2'
 * formatString('{tenantName} – Sourcing Command', { tenantName: 'L&T Construction' })
 */
export function formatString(template: string, values?: StringTemplateValues): string {
  if (!template || !values) {
    return template || '';
  }

  return template.replace(/\{(\w+)\}/g, (match, key) => {
    if (Object.prototype.hasOwnProperty.call(values, key) && values[key] !== undefined && values[key] !== null) {
      return String(values[key]);
    }
    return match;
  });
}

/**
 * Centralized UI Strings Dictionary (Single Source of Truth)
 *
 * Ensures all user-facing literal strings, titles, button labels, placeholders,
 * and dialog notices are extracted into dedicated constants for internationalization (i18n).
 */
export const UI_STRINGS: UIStringsDictionary = {
  common: {
    appName: 'ProCPX',
    appSubtitle: 'Multi-Tenant SaaS',
    appTagline: 'Enterprise Source-to-Award Procurement & AI Cost Intelligence',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Confirm',
    submit: 'Submit',
    back: 'Back',
    close: 'Close',
    export: 'Export',
    download: 'Download',
    viewDetails: 'View Details',
    search: 'Search',
    filter: 'Filter',
    status: 'Status',
    actions: 'Actions',
    category: 'Category',
    project: 'Project',
    vendor: 'Vendor',
    amount: 'Amount',
    quantity: 'Quantity',
    rate: 'Rate',
    date: 'Date',
    all: 'All',
    na: 'N/A',
    notAvailable: 'Not Available',
    active: 'Active',
    inactive: 'Inactive',
    success: 'Success',
    error: 'Error',
    warning: 'Warning',
    info: 'Info',
    selectOption: '-- Select Option --',
    showingResultsTemplate: 'Showing {count} results',
  },
  header: {
    brandName: 'ProCPX',
    brandBadge: 'Multi-Tenant SaaS',
    brandDescription: 'Enterprise Source-to-Award Procurement & AI Cost Intelligence',
    clientLabel: 'Client:',
    roleLabel: 'Role:',
    raisePRButton: 'Raise New PR',
    directPPOButton: '⚡ Direct PPO',
    switchRoleAria: 'Switch Governance Role',
    switchClientAria: 'Switch Active Client',
  },
  dashboard: {
    sourcingCommandTemplate: '{tenantName} – Sourcing Command',
    defaultTitle: 'Procurement & AI Cost Intelligence Hub',
    activePRs: 'Active PRs',
    workOrdersIssued: 'Work Orders Issued',
    stage1: '1. PR & BOQ',
    stage2: '2. Commercial Eval',
    stage3: '3. Negotiation',
    stage4: '4. PPO & PO',
    resetToSample: 'Reset to Sample Data',
    sourceToAwardPipeline: 'Source-to-Award Pipeline Status',
    quickActions: 'Quick Actions',
    spendAnalytics: 'Spend & Savings Analytics',
    totalSpend: 'Total Spend',
    projectedSavings: 'Projected Savings',
    negotiationYield: 'Negotiation Yield',
  },
  tenantOverview: {
    title: 'Multi-Tenancy Architecture & Corporate Roster',
    subtitle: 'Every enterprise client possesses independent project scopes, assigned personnel, and private rate cards.',
    gridTitle: 'Enterprise Clients & Assigned Personnel',
    gridSubtitle: 'Switching the active client dynamically scopes projects, cost centres, and role assignments across the entire platform.',
    activeProject: 'Active Project',
    assignedCostCentres: 'Assigned Cost Centres',
    governancePersonnel: 'Governance Personnel',
    currentActiveClient: 'Current Active Client',
    switchToClient: 'Switch to this Client',
    activeBadge: 'Active Scope',
  },
  prApprovalQueue: {
    title: 'Purchase Request Review & Authorization Inbox',
    subtitle: 'Review General details, Category mapping, BOQ specifications, Delivery location, and Attachments submitted by PR Raiser.',
    emptyTitle: 'No pending requisitions awaiting technical clearance',
    emptySubtitle: 'All raised requisitions have been cleared or routed to category managers.',
    approveButton: 'Approve PR & Route to Category Manager (Role 3)',
    rejectButton: 'Reject Requisition',
    approvedBadge: 'Authorized & Routed',
    pendingBadge: 'PENDING REVIEW',
    rejectedBadge: 'Rejected',
    viewBOQ: 'View BOQ',
    routeToCM: 'Route to Category Manager',
    clearanceRemarks: 'Technical Clearance Remarks',
  },
  mastersAudit: {
    title: 'Cost Centre Masters & Immutable Audit Trail',
    subtitle: 'Configure master data (Cost centres, categories, standard rate cards) and review tamper-proof event logs.',
    tableItem: 'Item Code',
    tableCategory: 'Category',
    tableBenchmark: 'Standard Master Rate Cards (FR-01)',
    tableRateCard: 'Standard Rate',
    tableVariance: 'Allowable Variance',
    tableUOM: 'UOM',
    tableStatus: 'Active FY 2026-27',
    auditTrailTitle: 'Immutable Audit Trail (Section 10)',
    auditTrailSubtitle: 'Cryptographically hashed event log tracking governance mutations.',
  },
  commercialEval: {
    title: 'Commercial Price Check & 4-Way Comparison',
    subtitle: 'Normalized 4-way commercial evaluation for drawing: Counter Elevation D (Millwork Package) with Line-Item MLEO Costing',
    l1Vendor: 'L1 Vendor',
    potentialSavings: 'Potential Savings',
    lowestQuoted: 'Lowest Quoted',
    targetBenchmark: 'Internal Benchmark',
    initiateNegotiation: 'Initiate AI Negotiation',
    comparativeSummary: 'Comparative Matrix',
    card1: '1. Master Rate Card Baseline',
    card2: '2. Lowest Vendor Quote (L1)',
    card3: '3. AI Market Benchmark',
    card4: '4. Internal Historical Std',
    proceedToPPO: 'Proceed to PPO',
    invokeAICosting: 'Invoke AI Costing',
    detailedAnalysis: 'Detailed MLEO Analysis',
  },
  negotiationHub: {
    title: 'Vendor Negotiation Hub (2-Round BAFO)',
    subtitle: 'Track multi-round counter-offers, revised 2nd quotes, target prices, and negotiation audit history.',
    vendorRate: 'Vendor Quoted Rate',
    targetRate: 'Target Benchmark Rate',
    currentRoundTemplate: 'Negotiation Round {round}',
    roundTemplate: 'Round {round}',
    generateCounterOffer: 'Generate AI Counter-Offer',
    recommendedRate: 'Recommended Counter Rate',
    strategyAdvice: 'Strategic Guidance',
    counterRemarks: 'Counter Remarks',
    acceptOffer: 'Accept Vendor Quote',
    submitCounter: 'Submit Counter-Offer',
    timelineTitle: 'Immutable Negotiation Audit Log & Multi-Round Timeline',
  },
  aiCostStudio: {
    badge: 'AI Cost Intelligence (FR-08, FR-09)',
    title: 'Bottom-Up MLEO Cost Analysis',
    subtitle: 'Deconstruct outlier rates into Material, Labour, Equipment, and Overheads (MLEO) to establish scientific negotiation leverage.',
    modelLabel: 'Model: ',
    modelEnvNote: 'Configurable via env (GEMINI_MODEL)',
    analyzeItemTitle: 'Analyze Procurement Item with Gemini',
    quickPresetsHint: 'Quick Presets or Custom Input',
    itemDescriptionLabel: 'Item Description / Specification:',
    itemDescriptionPlaceholder: 'e.g. Design Mix Concrete M30 with Fly Ash',
    quantityUomLabel: 'Quantity & UOM:',
    quotedRateLabel: 'Quoted Rate (₹):',
    analyzing: 'Analyzing...',
    runAnalysis: 'Run Gemini AI',
    activeAiEngine: 'Active AI Engine:',
    liveCostComplete: 'Live Cost Deconstruction Complete',
    costBreakdown: 'Cost Composition Engine (MLEO)',
    targetFairRate: 'Target Fair Rate',
    materials: '1. Material',
    labour: '2. Labour',
    equipment: '3. Equipment',
    overhead: '4. Overheads',
    materialsTemplate: '1. Material ({percentage}%)',
    labourTemplate: '2. Labour ({percentage}%)',
    equipmentTemplate: '3. Equipment ({percentage}%)',
    overheadTemplate: '4. Overheads ({percentage}%)',
    aiConfidence: 'AI Model Confidence',
    costInflatorsTitle: 'AI Identified Cost Inflators vs Market Benchmark:',
    buyerOverrideTitle: 'Buyer Cost Override & Target Formulation (AI-08 Human-in-the-Loop)',
    auditableDecision: 'Auditable Decision',
    recommendedTargetRate: 'Recommended Target Rate (₹):',
    maxWalkAwayLimit: 'Max Walk-Away Limit (₹):',
    sendToNegotiationHub: 'Send to Negotiation Hub →',
    negotiationScriptTitle: 'AI Negotiation Script & Rationales',
    negotiationScriptSubtitle: 'Auto-generated arguments based on market indices to use during vendor calls.',
    indicesVerified: 'Indices verified',
    geminiIntelligence: 'Gemini Intelligence',
  },
  boqStudio: {
    scopeBadge: 'Drawing Title Scope Guard',
    title: 'BOQ Extraction by Drawing Name',
    subtitle: 'As per drawing title (e.g. "Counter Elevation D"), extracts strictly and only the relevant specifications shown in that specific elevation.',
    drawingNameLabel: 'Drawing Name Mentioned in the Drawing:',
    drawingNamePlaceholder: 'e.g. Counter Elevation D',
    extractButton: 'Extract for this Drawing Name',
    quickPresets: 'Quick Presets:',
    scopedBoundary: 'Scoped Boundary:',
    addItem: 'Add BOQ Line Item',
    importDrawing: 'Import Drawing Scope',
    itemCode: 'Item Code',
    itemDescription: 'Specific Technical Description (As per Drawing Elevation D)',
    quantity: 'Quantity',
    uom: 'Unit',
    rateCardRate: 'Rate Card (₹)',
    totalAmount: 'Total Amount (₹)',
    specsSheet: 'Specs Sheet',
    action: 'Action',
    packageTotalLabel: 'Drawing Scope Package Total:',
    specsModalTitleTemplate: '{code} | Technical Specifications',
    close: 'Close',
    specsButton: 'Specs',
    commercialCheckButton: 'Validate & Start Commercial Check →',
    specsCountTemplate: 'Showing {count} line-items strictly corresponding to specifications shown on: {title}',
  },
  ppoModule: {
    title: 'Multi-Tier PPO Approval & Purchase Order Release',
    subtitle: 'Tier 1: Category Manager 2 → Tier 2: Project Head → Tier 3: Finance Head & PO Release.',
    tabWorkflow: '3-Tier Approval Workflow',
    tabAllPPOsTemplate: 'All PPOs ({count})',
    tabIssuedPOsTemplate: 'Issued POs ({count})',
    badgePoReleased: 'PO RELEASED',
    badgeTier3InProgress: 'TIER 3 IN PROGRESS',
    badgeTier2InProgress: 'TIER 2 IN PROGRESS',
    badgeTier1InProgress: 'TIER 1 IN PROGRESS',
    tier1Title: 'Tier 1: Category Manager 2',
    tier1Desc: 'Commercial savings validation & strategic sourcing compliance.',
    tier1SignOff: '✓ Sign-off Tier 1 (Cat Mgr 2)',
    tier1SignedTemplate: 'Signed by {name}',
    tier2Title: 'Tier 2: Project Head',
    tier2Desc: 'Site budget clearance & milestone sign-off.',
    tier2SignOff: '✓ Sign-off Tier 2 (Project Head)',
    tier2SignedTemplate: 'Signed by {name}',
    tier3Title: 'Tier 3: Finance Head',
    tier3Desc: 'Commercial audit & Release Purchase Order.',
    tier3SignOff: '✓ Release Purchase Order (PO)',
    tier3SignedTemplate: 'Signed by {name}',
    badgeApproved: 'APPROVED ✓',
    badgePending: 'PENDING',
    badgeAwaitingTier1: 'AWAITING TIER 1',
    badgeAwaitingTier2: 'AWAITING TIER 2',
    badgeApprovedIssued: 'APPROVED & ISSUED ✓',
    badgePendingSignOff: 'PENDING SIGN-OFF',
    badgePendingFinalAudit: 'PENDING FINAL AUDIT',
    poReleasedBannerTitleTemplate: '🎉 Purchase Order {poNumber} Officially Issued!',
    poReleasedBannerDesc: 'All 3 approval tiers passed. Signed contract document ready for download.',
    downloadOfficialPdfTemplate: 'Download Official {poNumber} PDF',
    allPPOsTitle: 'Purchase Price Offers (PPOs)',
    createPPO: 'Create PPO',
    releasePO: 'Release Official Purchase Order',
    commercialTerms: 'Commercial & Payment Terms',
    deliverySchedule: 'Delivery Schedule & Lead Time',
    taxRate: 'Tax / GST Rate',
    totalCommitment: 'Total Commercial Commitment',
    poNumberTemplate: 'Purchase Order #{poNumber}',
    ppoNumberTemplate: 'PPO #{ppoNumber}',
    issuedPOsTitle: 'Released Purchase Orders / Work Orders',
    downloadPdfButton: 'Download PDF PO',
    approvePPOButton: 'Approve PPO',
  },
  vendorPortal: {
    title: 'Vendor Partner Quotation & Bidding Portal',
    subtitle: 'Direct enterprise vendor interface to review RFQs, submit quotation rates, and track award status.',
    rfqList: 'Open RFQs & Bidding Invitations',
    submitQuote: 'Submit Quotation',
    quoteStatus: 'Quote Status',
    counterOffers: 'Active Counter-Offers',
    awardedPOs: 'Awarded Purchase Orders',
    roleBadge: 'Role 7: Vendor Portal & Supplier Workbench',
    activeRfqLabel: 'Active RFQ:',
    vendorLabel: 'Vendor:',
    rfqLabel: 'RFQ:',
    tabQuote1: '1. 1st Round Quote (Pricing & Terms)',
    tabQuote2: '2. 2nd Quote / BAFO (with 1st Quote Comparison & Terms)',
    tabFinal: '3. Final Quote & Multi-Round Summary',
    tabPPO: '4. PPO Award Review & Acceptance Console',
    acceptRfq: 'Accept RFQ',
    rfqAccepted: '✓ RFQ Accepted & Confirmed',
    pendingAcceptance: 'Action: Pending Acceptance',
    activeBidder: 'Active Bidder',
    reviewOffer: 'Review Offer →',
    viewPO: 'View PO',
    submitQuote1: 'Submit 1st Round Formal Quotation (Pricing + Terms) →',
    submitQuote2: 'Submit Revised 2nd Quote / BAFO (Pricing + Terms) →',
    quote1Submitted: '1st Round Quotation Submitted ✓',
    quote2Submitted: 'Revised 2nd Quote Submitted ✓',
    acceptPPO: 'Accept Purchase Price Offer (PPO)',
    downloadPO: 'Download Signed PO PDF',
    orderAcknowledged: 'Order Acknowledged & Binding Contract Activated ✓',
    historyTitle: 'Multi-Round Quotation History & Final Settlement Record',
    round1SubmittedNotice: 'Round 1: Submitted ✓',
    round2SubmittedNotice: 'Round 2: Submitted ✓',
  },
  prModule: {
    title: 'Purchase Requisition Management',
    subtitle: 'Create, track, and manage material and service requisitions.',
    newPR: 'New Requisition',
    prNumber: 'PR Number',
    project: 'Project',
    costCentre: 'Cost Centre',
    requester: 'Requester',
    status: 'Status',
    itemsCountTemplate: '{count} Items',
    roleBadge: 'PR Raiser Scope (Role 1)',
    draftIdTemplate: 'Draft ID: {id}',
    stepGeneral: 'General',
    stepCategory: 'Category Selection',
    stepBOQ: 'BOQ Studio (PR Items)',
    stepSuppliers: 'Supplier Selection',
    stepDelivery: 'Delivery Locations',
    stepTerms: 'Terms & Conditions',
    stepDocuments: 'Documents',
    submitToProjectHead: 'Submit PR with BOQ to Project Head',
    cancelPR: 'Cancel PR Creation',
    nextStep: 'Next',
    prevStep: 'Previous',
  },
  categoryManagerHub: {
    title: 'Category Manager Procurement Hub',
    subtitle: 'Commercial strategy, vendor negotiations, comparative evaluation, and award approvals.',
    vendorAllocation: 'Vendor Allocation',
    sourcingStrategy: 'Sourcing Strategy',
    spendOverview: 'Category Spend Overview',
    roleBadge: 'Role 3: Category Manager (Buyer Command Center)',
    tabRFQ: '1. RFQ & Vendor Tender Management',
    tabRateCard: '2. Master Rate Card Studio',
    tabCommercial: '3. 4-Way Commercial Matrix & CBA',
    tabAICost: '4. AI Cost Benchmarking & MLEO',
    tabNegotiation: '5. Vendor Negotiation Hub',
    tabPPO: '6. PPO Proposal & Routing',
    raiseRFQ: 'Raise / Manage RFQ',
    cbaMatrix: '4-Way Matrix (CBA)',
    awardPPO: 'Award PPO',
    awardL1: 'Award PPO (L1) →',
    awardNonL1: 'Award PPO (Non-L1) →',
    mleoBreakdown: 'MLEO BREAKDOWN',
    backToCommercial: '← Back to Commercial Matrix',
    routePPOToWorkflow: 'Route PPO to Tier 1 Approval Workflow →',
  },
  modals: {
    newPRTitle: 'Raise New Purchase Requisition (PR)',
    newPRSubtitle: 'Initiate a technical requisition package for governance review and commercial sourcing.',
    targetProject: 'Target Project',
    prPackageTitle: 'Requisition Title / Package Name',
    estimatedDate: 'Estimated Required By Date',
    costCentre: 'Cost Centre',
    category: 'Category',
    itemScope: 'Item Scope & Specifications',
    remarks: 'Technical Justification & Site Remarks',
    submitPR: 'Submit Requisition',
    newPPOTitle: 'Draft Direct Pre-Purchase Order (PPO)',
    newPPOSubtitle: 'Fast-track commercial commitment and generate award documentation.',
    targetPR: 'Target Requisition (PR)',
    selectedVendor: 'Selected Vendor Partner',
    agreedUnitRate: 'Agreed Unit Rate (excl. Tax)',
    taxRate: 'Applicable GST / Tax Rate (%)',
    paymentTerms: 'Commercial Payment Terms',
    leadTime: 'Promised Delivery Lead Time',
    createPPOButton: 'Create PPO & Work Order',
  },
};
