import { VendorItem, VendorQuoteItem } from '@/types';

export const VENDOR_DATABASE: VendorItem[] = [
  // INTERIOR & FITOUTS - WEST
  {
    id: 'VND-001',
    name: 'Vendor 1',
    category: 'Interior & Fitouts',
    subCategory: 'Millwork, Joinery & Counter Fabrication',
    region: 'WEST',
    regionLabel: 'West (Mumbai / Pune / Gujarat)',
    rating: 4.9,
    reviewsCount: 48,
    isRateCard: true,
    rateCardCode: 'RC-2026-INT-01',
    rateCardStatus: 'Active (Valid till Dec 2026)',
    contactPerson: 'Vendor 1 Key Contact',
    gstin: '27AAACD4567M1Z4',
    city: 'Mumbai, Maharashtra',
    leadTime: '7-10 Days',
    badgeText: 'Rate Card Vendor (Contracted)',
    capacity: 'High'
  },
  {
    id: 'VND-002',
    name: 'Vendor 2',
    category: 'Interior & Fitouts',
    subCategory: 'Millwork, Joinery & Counter Fabrication',
    region: 'WEST',
    regionLabel: 'West (Mumbai / Pune / Gujarat)',
    rating: 4.8,
    reviewsCount: 72,
    isRateCard: true,
    rateCardCode: 'RC-2026-INT-02',
    rateCardStatus: 'Active (Valid till Mar 2027)',
    contactPerson: 'Vendor 2 Key Contact',
    gstin: '27AAACG1234L1Z8',
    city: 'Pune, Maharashtra',
    leadTime: '10-14 Days',
    badgeText: 'Rate Card Vendor (Contracted)',
    capacity: 'Enterprise'
  },
  {
    id: 'VND-003',
    name: 'Vendor 3',
    category: 'Interior & Fitouts',
    subCategory: 'Millwork, Joinery & Counter Fabrication',
    region: 'WEST',
    regionLabel: 'West (Mumbai / Pune / Gujarat)',
    rating: 4.3,
    reviewsCount: 29,
    isRateCard: false,
    rateCardCode: null,
    rateCardStatus: 'Empanelled',
    contactPerson: 'Vendor 3 Key Contact',
    gstin: '24AAACP9988K1ZW',
    city: 'Ahmedabad, Gujarat',
    leadTime: '12-15 Days',
    badgeText: 'Non-Rate Card Vendor (Empanelled)',
    capacity: 'Medium'
  },
  {
    id: 'VND-004',
    name: 'Vendor 4',
    category: 'Interior & Fitouts',
    subCategory: 'Millwork, Joinery & Counter Fabrication',
    region: 'WEST',
    regionLabel: 'West (Mumbai / Pune / Gujarat)',
    rating: 4.1,
    reviewsCount: 18,
    isRateCard: false,
    rateCardCode: null,
    rateCardStatus: 'Open Market',
    contactPerson: 'Vendor 4 Key Contact',
    gstin: '27AAACS1122J1Z1',
    city: 'Thane, Maharashtra',
    leadTime: '14-18 Days',
    badgeText: 'Non-Rate Card Vendor (Open Market)',
    capacity: 'Small-Medium'
  },
  // INTERIOR & FITOUTS - NORTH
  {
    id: 'VND-005',
    name: 'Vendor 5',
    category: 'Interior & Fitouts',
    subCategory: 'Millwork, Joinery & Counter Fabrication',
    region: 'NORTH',
    regionLabel: 'North (Delhi-NCR / Haryana / UP)',
    rating: 4.7,
    reviewsCount: 38,
    isRateCard: true,
    rateCardCode: 'RC-2026-INT-03',
    rateCardStatus: 'Active (Valid till Nov 2026)',
    contactPerson: 'Vendor 5 Key Contact',
    gstin: '07AAACD9911P1ZK',
    city: 'New Delhi, NCR',
    leadTime: '8-12 Days',
    badgeText: 'Rate Card Vendor (Contracted)',
    capacity: 'High'
  },
  {
    id: 'VND-006',
    name: 'Vendor 6',
    category: 'Interior & Fitouts',
    subCategory: 'Millwork, Joinery & Counter Fabrication',
    region: 'NORTH',
    regionLabel: 'North (Delhi-NCR / Haryana / UP)',
    rating: 4.2,
    reviewsCount: 22,
    isRateCard: false,
    rateCardCode: null,
    rateCardStatus: 'Empanelled',
    contactPerson: 'Vendor 6 Key Contact',
    gstin: '09AAACN5544H1ZX',
    city: 'Noida, Uttar Pradesh',
    leadTime: '12-16 Days',
    badgeText: 'Non-Rate Card Vendor (Empanelled)',
    capacity: 'Medium'
  },
  // INTERIOR & FITOUTS - SOUTH
  {
    id: 'VND-007',
    name: 'Vendor 7',
    category: 'Interior & Fitouts',
    subCategory: 'Millwork, Joinery & Counter Fabrication',
    region: 'SOUTH',
    regionLabel: 'South (Bengaluru / Chennai / Hyderabad)',
    rating: 4.9,
    reviewsCount: 54,
    isRateCard: true,
    rateCardCode: 'RC-2026-INT-04',
    rateCardStatus: 'Active (Valid till Jan 2027)',
    contactPerson: 'Vendor 7 Key Contact',
    gstin: '29AAACS8810K1ZD',
    city: 'Bengaluru, Karnataka',
    leadTime: '10-12 Days',
    badgeText: 'Rate Card Vendor (Contracted)',
    capacity: 'High'
  },
  {
    id: 'VND-008',
    name: 'Vendor 8',
    category: 'Interior & Fitouts',
    subCategory: 'Millwork, Joinery & Counter Fabrication',
    region: 'SOUTH',
    regionLabel: 'South (Bengaluru / Chennai / Hyderabad)',
    rating: 4.2,
    reviewsCount: 19,
    isRateCard: false,
    rateCardCode: null,
    rateCardStatus: 'Empanelled',
    contactPerson: 'Vendor 8 Key Contact',
    gstin: '33AAACT7721N1ZM',
    city: 'Chennai, Tamil Nadu',
    leadTime: '15-18 Days',
    badgeText: 'Non-Rate Card Vendor (Empanelled)',
    capacity: 'Medium'
  },
  // INTERIOR & FITOUTS - EAST
  {
    id: 'VND-009',
    name: 'Vendor 9',
    category: 'Interior & Fitouts',
    subCategory: 'Millwork, Joinery & Counter Fabrication',
    region: 'EAST',
    regionLabel: 'East (Kolkata / Odisha / North-East)',
    rating: 4.6,
    reviewsCount: 34,
    isRateCard: true,
    rateCardCode: 'RC-2026-INT-05',
    rateCardStatus: 'Active (Valid till Dec 2026)',
    contactPerson: 'Vendor 9 Key Contact',
    gstin: '19AAACB6621R1ZW',
    city: 'Kolkata, West Bengal',
    leadTime: '14-16 Days',
    badgeText: 'Rate Card Vendor (Contracted)',
    capacity: 'High'
  },
  {
    id: 'VND-010',
    name: 'Vendor 10',
    category: 'Interior & Fitouts',
    subCategory: 'Millwork, Joinery & Counter Fabrication',
    region: 'EAST',
    regionLabel: 'East (Kolkata / Odisha / North-East)',
    rating: 4.0,
    reviewsCount: 15,
    isRateCard: false,
    rateCardCode: null,
    rateCardStatus: 'Open Market',
    contactPerson: 'Vendor 10 Key Contact',
    gstin: '19AAECB1123Q1ZR',
    city: 'Bhubaneswar, Odisha',
    leadTime: '20-22 Days',
    badgeText: 'Non-Rate Card Vendor (Open Market)',
    capacity: 'Small-Medium'
  },
  // CIVIL - WEST
  {
    id: 'VND-011',
    name: 'Vendor 11',
    category: 'Civil Infrastructure',
    subCategory: 'Concrete Foundations & Substructure',
    region: 'WEST',
    regionLabel: 'West (Mumbai / Pune / Gujarat)',
    rating: 4.9,
    reviewsCount: 110,
    isRateCard: true,
    rateCardCode: 'RC-2026-CIV-01',
    rateCardStatus: 'Active (Valid till Mar 2027)',
    contactPerson: 'Vendor 11 Key Contact',
    gstin: '27AAACU1234N1ZT',
    city: 'Navi Mumbai, Maharashtra',
    leadTime: '3-5 Days',
    badgeText: 'Rate Card Vendor (Contracted)',
    capacity: 'Mega Enterprise'
  },
  {
    id: 'VND-012',
    name: 'Vendor 12',
    category: 'Civil Infrastructure',
    subCategory: 'Concrete Foundations & Substructure',
    region: 'WEST',
    regionLabel: 'West (Mumbai / Pune / Gujarat)',
    rating: 4.7,
    reviewsCount: 84,
    isRateCard: true,
    rateCardCode: 'RC-2026-CIV-02',
    rateCardStatus: 'Active (Valid till Dec 2026)',
    contactPerson: 'Vendor 12 Key Contact',
    gstin: '27AAACA9921B1ZU',
    city: 'Thane, Maharashtra',
    leadTime: '4-6 Days',
    badgeText: 'Rate Card Vendor (Contracted)',
    capacity: 'Enterprise'
  },
  {
    id: 'VND-013',
    name: 'Vendor 13',
    category: 'Civil Infrastructure',
    subCategory: 'Concrete Foundations & Substructure',
    region: 'WEST',
    regionLabel: 'West (Mumbai / Pune / Gujarat)',
    rating: 4.1,
    reviewsCount: 31,
    isRateCard: false,
    rateCardCode: null,
    rateCardStatus: 'Empanelled',
    contactPerson: 'Vendor 13 Key Contact',
    gstin: '27AAHCS4412K1ZW',
    city: 'Panvel, Maharashtra',
    leadTime: '7-10 Days',
    badgeText: 'Non-Rate Card Vendor (Empanelled)',
    capacity: 'Medium'
  },
  // MEP - WEST
  {
    id: 'VND-014',
    name: 'Vendor 14',
    category: 'MEP & HVAC',
    subCategory: 'HVAC Chillers & Ducting',
    region: 'WEST',
    regionLabel: 'West (Mumbai / Pune / Gujarat)',
    rating: 4.9,
    reviewsCount: 95,
    isRateCard: true,
    rateCardCode: 'RC-2026-MEP-01',
    rateCardStatus: 'Active (Valid till Dec 2026)',
    contactPerson: 'Vendor 14 Key Contact',
    gstin: '27AAACB1100C1ZY',
    city: 'Mumbai, Maharashtra',
    leadTime: '15-20 Days',
    badgeText: 'Rate Card Vendor (Contracted)',
    capacity: 'Enterprise OEM'
  },
  {
    id: 'VND-015',
    name: 'Vendor 15',
    category: 'MEP & HVAC',
    subCategory: 'HVAC Chillers & Ducting',
    region: 'WEST',
    regionLabel: 'West (Mumbai / Pune / Gujarat)',
    rating: 4.8,
    reviewsCount: 88,
    isRateCard: true,
    rateCardCode: 'RC-2026-MEP-02',
    rateCardStatus: 'Active (Valid till Jan 2027)',
    contactPerson: 'Vendor 15 Key Contact',
    gstin: '27AAACV2231E1ZZ',
    city: 'Mumbai, Maharashtra',
    leadTime: '14-18 Days',
    badgeText: 'Rate Card Vendor (Contracted)',
    capacity: 'Enterprise OEM'
  },
  {
    id: 'VND-016',
    name: 'Vendor 16',
    category: 'MEP & HVAC',
    subCategory: 'HVAC Chillers & Ducting',
    region: 'WEST',
    regionLabel: 'West (Mumbai / Pune / Gujarat)',
    rating: 4.2,
    reviewsCount: 26,
    isRateCard: false,
    rateCardCode: null,
    rateCardStatus: 'Empanelled',
    contactPerson: 'Vendor 16 Key Contact',
    gstin: '27AAHCC8812D1ZR',
    city: 'Pune, Maharashtra',
    leadTime: '20-25 Days',
    badgeText: 'Non-Rate Card Vendor (Empanelled)',
    capacity: 'Medium'
  }
];

export const MASTER_VENDORS = [
  { id: 'VND-001', name: 'Vendor 1', category: 'INTERIOR', rating: 4.9, isRateCard: true, city: 'Mumbai', leadTime: '12-15 Days' },
  { id: 'VND-002', name: 'Vendor 2', category: 'INTERIOR', rating: 4.8, isRateCard: true, city: 'Pune', leadTime: '10-14 Days' },
  { id: 'VND-003', name: 'Vendor 3', category: 'INTERIOR', rating: 4.3, isRateCard: false, city: 'Ahmedabad', leadTime: '18-20 Days' },
  { id: 'VND-004', name: 'Vendor 4', category: 'INTERIOR', rating: 3.9, isRateCard: false, city: 'Thane', leadTime: '20-25 Days' },
  { id: 'VND-005', name: 'Vendor 5', category: 'INTERIOR', rating: 4.7, isRateCard: true, city: 'Noida', leadTime: '12-14 Days' },
  { id: 'VND-007', name: 'Vendor 7', category: 'INTERIOR', rating: 4.8, isRateCard: true, city: 'Bengaluru', leadTime: '10-12 Days' },
  { id: 'VND-011', name: 'Vendor 11', category: 'CIVIL', rating: 4.9, isRateCard: true, city: 'Navi Mumbai', leadTime: '3-5 Days' },
  { id: 'VND-012', name: 'Vendor 12', category: 'CIVIL', rating: 4.7, isRateCard: true, city: 'Thane', leadTime: '4-6 Days' },
  { id: 'VND-013', name: 'Vendor 13', category: 'CIVIL', rating: 4.1, isRateCard: false, city: 'Panvel', leadTime: '7-10 Days' },
  { id: 'VND-014', name: 'Vendor 14', category: 'MEP', rating: 4.9, isRateCard: true, city: 'Mumbai', leadTime: '15-20 Days' },
  { id: 'VND-015', name: 'Vendor 15', category: 'MEP', rating: 4.8, isRateCard: true, city: 'Mumbai', leadTime: '14-18 Days' },
  { id: 'VND-016', name: 'Vendor 16', category: 'MEP', rating: 4.2, isRateCard: false, city: 'Pune', leadTime: '20-25 Days' }
];

export const INITIAL_VENDOR_QUOTE_ITEMS: VendorQuoteItem[] = [
  { code: 'CNT-TOP-GRN20', desc: '20mm Polished Jet Black Granite Countertop', uom: 'Sqm', qty: 12.5, rate1: 3900, targetRate: 3380, rate2: 3650 },
  { code: 'CNT-PLY-BWP18', desc: '18mm Marine Grade BWP Plywood (IS 710)', uom: 'Sqm', qty: 38.0, rate1: 1650, targetRate: 1435, rate2: 1540 },
  { code: 'CNT-LAM-1MM', desc: '1.0mm Textured HPL Laminate Fascia', uom: 'Sqm', qty: 24.0, rate1: 980, targetRate: 850, rate2: 910 },
  { code: 'CNT-HDW-SOFT', desc: 'Soft-Close Concealed Hinges & Telescopic Slides', uom: 'Set', qty: 14.0, rate1: 2100, targetRate: 1715, rate2: 1950 },
  { code: 'CNT-LED-PROF', desc: '12V DC Warm White LED Strip in Profile', uom: 'Rmt', qty: 16.0, rate1: 450, targetRate: 365, rate2: 410 },
  { code: 'CNT-SKT-SS304', desc: '100mm SS 304 Brushed Skirting', uom: 'Rmt', qty: 14.0, rate1: 850, targetRate: 705, rate2: 780 }
];
